# Generated by Django 4.2.21 on 2025-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.city'),
        ),
    ]
