# Generated by Django 4.2.21 on 2025-05-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('temperature', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('humidity', models.CharField(blank=True, max_length=10)),
                ('wind', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
